// ─── 임시 데이터 ──────────────────────────────────────────────────────────────
// TODO: API 연동 시 전부 서버 응답으로 교체.
// 단가·금액·확정 여부 등 계산 값은 모두 "서버가 계산해 내려준 값"이라는 전제.

// 시장 현황 배너 (기준 날짜가 서로 다를 수 있음)
export const MOCK_MARKET = {
  lme: { value: 9484.5, date: "2026-07-08" }, // USD/ton
  exchangeRate: { value: 1382.4, date: "2026-07-09" }, // 원/USD
};

export const MOCK_CONTRACTS = [
  {
    id: 1,
    name: "포스코 A동 수출 계약",
    contractNo: "CT-2026-001",
    company: "포스코인터내셔널",
    status: "진행중",
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    tradeType: "수출",
    priceUnit: "TON",
    quantity: 100000, // kg 저장 (톤 계약 → 표시만 100 톤)
    memo: "선적 전 품질검사 필수",
    prices: [
      {
        id: "p1",
        type: "가단가",
        periodStart: "2026-07-01",
        periodEnd: "2026-07-31",
        formulaId: "PERIOD_AVG",
        formulaName: "산정기간 평균",
        fixedPrice: null,
        confirmed: true,
        lme: 9450.0,
        exchangeRate: null,
        krwPerKg: 11998, // 목록 카드용 원/kg (대표 품목 기준, 서버 계산)
      },
      {
        id: "p2",
        type: "확정가",
        periodStart: "2026-08-01",
        periodEnd: "2026-08-31",
        formulaId: "MONTH_AVG",
        formulaName: "월평균",
        fixedPrice: null,
        confirmed: true,
        lme: 9520.0,
        exchangeRate: null,
        krwPerKg: 12105,
      },
      {
        id: "p3",
        type: "정산가",
        periodStart: "2026-07-01",
        periodEnd: "2026-08-31",
        formulaId: "PERIOD_AVG",
        formulaName: "산정기간 평균",
        fixedPrice: null,
        confirmed: false,
        lme: 9484.5,
        exchangeRate: null,
        krwPerKg: 12052,
      },
    ],
    items: [
      {
        id: "i1",
        name: "A동",
        isPrimary: true,
        // priceId → { rate(%), premium(계약 통화), value(계약 통화·단위 단가, 서버 계산) }
        options: {
          p1: { rate: 96.5, premium: 50, value: 9169.25 },
          p2: { rate: 96.5, premium: 50, value: 9236.8 },
          p3: { rate: 96.5, premium: null, value: 9152.55 },
        },
      },
      {
        id: "i2",
        name: "B동",
        isPrimary: false,
        options: {
          p1: { rate: 94.0, premium: null, value: 8883.0 },
          p2: { rate: 94.0, premium: null, value: 8948.8 },
          p3: { rate: 94.0, premium: null, value: 8915.43 },
        },
      },
    ],
    transactions: [
      {
        id: "t1",
        date: "2026-07-03",
        itemName: "A동",
        priceType: "가단가",
        quantity: 24,
        unitPrice: 9169.25,
        totalAmount: 220062.0,
        paid: true,
        payment: {
          foreignAmount: 220062.0,
          exchangeRate: 1381.2,
          krwAmount: 303949637,
          depositDate: "2026-07-06",
        },
      },
      {
        id: "t2",
        date: "2026-07-07",
        itemName: "B동",
        priceType: "가단가",
        quantity: 18,
        unitPrice: 8883.0,
        totalAmount: 159894.0,
        paid: false,
        payment: null,
      },
    ],
  },
  {
    id: 2,
    name: "한국전선 상동 공급 계약",
    contractNo: "CT-2026-002",
    company: "한국전선(주)",
    status: "진행중",
    startDate: "2026-07-01",
    endDate: "2026-12-31",
    tradeType: "내수",
    priceUnit: "KG",
    quantity: 50000,
    memo: "월말 일괄 정산",
    prices: [
      {
        id: "p1",
        type: "가단가",
        periodStart: "2026-07-01",
        periodEnd: "2026-09-30",
        formulaId: "MONTH_AVG",
        formulaName: "월평균",
        fixedPrice: null,
        confirmed: true,
        lme: 9430.0,
        exchangeRate: 1379.8,
        krwPerKg: 12240,
      },
      {
        id: "p2",
        type: "확정가",
        periodStart: "2026-10-01",
        periodEnd: "2026-12-31",
        formulaId: "PERIOD_AVG",
        formulaName: "산정기간 평균",
        fixedPrice: null,
        confirmed: false, // 미확정 → 정산가 줄 숨김
        lme: null,
        exchangeRate: null,
        krwPerKg: null,
      },
      {
        id: "p3",
        type: "정산가",
        periodStart: "2026-07-01",
        periodEnd: "2026-12-31",
        formulaId: "PERIOD_AVG",
        formulaName: "산정기간 평균",
        fixedPrice: null,
        confirmed: false,
        lme: null,
        exchangeRate: null,
        krwPerKg: null,
      },
    ],
    items: [
      {
        id: "i1",
        name: "상동",
        isPrimary: true,
        options: {
          p1: { rate: 97.0, premium: 100, value: 12240 },
          p2: { rate: 97.0, premium: 100, value: null },
          p3: { rate: 97.0, premium: null, value: null },
        },
      },
    ],
    transactions: [
      {
        id: "t1",
        date: "2026-07-05",
        itemName: "상동",
        priceType: "가단가",
        quantity: 12000,
        unitPrice: 12240,
        totalAmount: 146880000,
        paid: false,
        payment: null,
      },
    ],
  },
  {
    id: 3,
    name: "LS전선 파동 수출 계약",
    contractNo: "CT-2026-003",
    company: "LS전선(주)",
    status: "완료",
    startDate: "2026-01-01",
    endDate: "2026-06-30",
    tradeType: "수출",
    priceUnit: "TON",
    quantity: 80000, // 80 톤
    memo: "", // 비고 없음 (조용한 영역 숨김 확인용)
    prices: [
      {
        id: "p1",
        type: "원가",
        periodStart: "2026-01-01",
        periodEnd: "2026-06-30",
        formulaId: "FIXED",
        formulaName: "고정값",
        fixedPrice: 9200.0,
        confirmed: true,
        lme: 9200.0,
        exchangeRate: null,
        krwPerKg: 11730,
      },
      {
        id: "p2",
        type: "확정가",
        periodStart: "2026-04-01",
        periodEnd: "2026-06-30",
        formulaId: "PERIOD_AVG",
        formulaName: "산정기간 평균",
        fixedPrice: null,
        confirmed: true,
        lme: 9315.5,
        exchangeRate: null,
        krwPerKg: 11877,
      },
      {
        id: "p3",
        type: "정산가",
        periodStart: "2026-01-01",
        periodEnd: "2026-06-30",
        formulaId: "PERIOD_AVG",
        formulaName: "산정기간 평균",
        fixedPrice: null,
        confirmed: true,
        lme: 9260.75,
        exchangeRate: null,
        krwPerKg: 11804,
      },
    ],
    items: [
      {
        id: "i1",
        name: "파동",
        isPrimary: true,
        options: {
          p1: { rate: 92.0, premium: null, value: 8464.0 },
          p2: { rate: 92.0, premium: null, value: 8570.26 },
          p3: { rate: 92.0, premium: null, value: 8519.89 },
        },
      },
    ],
    transactions: [
      {
        id: "t1",
        date: "2026-03-14",
        itemName: "파동",
        priceType: "확정가",
        quantity: 40,
        unitPrice: 8570.26,
        totalAmount: 342810.4,
        paid: true,
        payment: {
          foreignAmount: 342810.4,
          exchangeRate: 1375.0,
          krwAmount: 471364300,
          depositDate: "2026-03-20",
        },
      },
    ],
  },
  {
    id: 4,
    name: "동국제강 밀베리 공급 계약",
    contractNo: "CT-2026-004",
    company: "동국제강(주)",
    status: "진행중",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    tradeType: "내수",
    priceUnit: "KG",
    quantity: 30000,
    memo: "",
    prices: [
      {
        id: "p1",
        type: "가단가",
        periodStart: "2026-06-01",
        periodEnd: "2026-08-31",
        formulaId: "PERIOD_AVG",
        formulaName: "산정기간 평균",
        fixedPrice: null,
        confirmed: true,
        lme: 9401.25,
        exchangeRate: 1377.6,
        krwPerKg: 12105,
      },
    ],
    items: [
      {
        id: "i1",
        name: "밀베리",
        isPrimary: true,
        options: {
          p1: { rate: 98.5, premium: null, value: 12105 },
        },
      },
    ],
    transactions: [],
  },
];
